"""SIZE ENUM

Revision ID: 7994fab7243a
Revises: 48d2d496f905
Create Date: 2023-08-07 22:03:36.331402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7994fab7243a'
down_revision = '48d2d496f905'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
